/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Settings, Settings, AUTO)

PB_BIND(Transmission, Transmission, 2)

PB_BIND(Gps, Gps, AUTO)

PB_BIND(Log, Log, 2)

PB_BIND(Request, Request, AUTO)

PB_BIND(Packet, Packet, 2)

#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
