/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Settings, Settings, AUTO)


PB_BIND(Transmission, Transmission, 2)


PB_BIND(Packet, Packet, 2)





