# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packet.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'packet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpacket.proto\"\xb8\x01\n\x08Settings\x12\x11\n\tfrequency\x18\x01 \x01(\x02\x12\r\n\x05power\x18\x02 \x01(\x05\x12\x11\n\tbandwidth\x18\x03 \x01(\x02\x12\x18\n\x10spreading_factor\x18\x04 \x01(\x05\x12\x13\n\x0b\x63oding_rate\x18\x05 \x01(\x05\x12\x10\n\x08preamble\x18\x06 \x01(\x05\x12\x0f\n\x07set_crc\x18\x07 \x01(\x08\x12\x11\n\tsync_word\x18\x08 \x01(\r\x12\x12\n\nfunc_state\x18\t \x01(\x08\"\x1f\n\x0cTransmission\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x99\x01\n\x08Received\x12\x11\n\tcrc_error\x18\x01 \x01(\x08\x12\x15\n\rgeneral_error\x18\x02 \x01(\x08\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x12\n\nsattelites\x18\x05 \x01(\r\x12\x0c\n\x04rssi\x18\x06 \x01(\x02\x12\x0b\n\x03snr\x18\x07 \x01(\x02\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\"\x82\x01\n\x06Packet\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.PacketType\x12\x1b\n\x08settings\x18\x02 \x01(\x0b\x32\t.Settings\x12#\n\x0ctransmission\x18\x03 \x01(\x0b\x32\r.Transmission\x12\x1b\n\x08received\x18\x04 \x01(\x0b\x32\t.Received*=\n\nPacketType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08SETTINGS\x10\x01\x12\x10\n\x0cTRANSMISSION\x10\x02**\n\tFuncState\x12\x0f\n\x0bTRANSMITTER\x10\x00\x12\x0c\n\x08RECEIVER\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKETTYPE']._serialized_start=525
  _globals['_PACKETTYPE']._serialized_end=586
  _globals['_FUNCSTATE']._serialized_start=588
  _globals['_FUNCSTATE']._serialized_end=630
  _globals['_SETTINGS']._serialized_start=17
  _globals['_SETTINGS']._serialized_end=201
  _globals['_TRANSMISSION']._serialized_start=203
  _globals['_TRANSMISSION']._serialized_end=234
  _globals['_RECEIVED']._serialized_start=237
  _globals['_RECEIVED']._serialized_end=390
  _globals['_PACKET']._serialized_start=393
  _globals['_PACKET']._serialized_end=523
# @@protoc_insertion_point(module_scope)
