# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: settings.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esettings.proto\"\xa4\x01\n\x08Settings\x12\x11\n\tfrequency\x18\x01 \x01(\x02\x12\r\n\x05power\x18\x02 \x01(\x05\x12\x11\n\tbandwidth\x18\x03 \x01(\x02\x12\x18\n\x10spreading_factor\x18\x04 \x01(\x05\x12\x13\n\x0b\x63oding_rate\x18\x05 \x01(\x05\x12\x10\n\x08preamble\x18\x06 \x01(\x05\x12\x0f\n\x07set_crc\x18\x07 \x01(\x08\x12\x11\n\tsync_word\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETTINGS']._serialized_start=19
  _globals['_SETTINGS']._serialized_end=183
# @@protoc_insertion_point(module_scope)
